echo "IMPORTANT!"
echo "THIS PAYLOAD WILL STOP YOUR CHROMEBOOK FROM UPDATING PAST 105"
echo "IF YOU DON'T DO THIS, AFTER UPDATING PAST 109 THIS EXPLOIT WILL BE PATCHED AND YOU WON'T BE ABLE TO GO BACK HERE"
echo "IF YOU RECOVER YOUR CHROMEBOOK THESE CHANGES GO AWAY, MAKE SURE TO DO THIS AGAIN"

sleep 5
mkdir /tmp/m
mount /dev/mmcblk0p1 /tmp/m
printf "CHROMEOS_RELEASE_VERSION=9999.9999.9999.9999\nGOOGLE_RELEASE=9999.9999.9999.9999" >>/tmp/m/etc/lsb-release
sleep 1
read "Done. Press enter to continue"
